-- Inserir musicas no repertorio
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Smells Like Teen Spirit', 'Nirvana', '70-90', '{"Grunge","Rock"}', 'assets/audio/demo.mp3', false, 0);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Black', 'Pearl Jam', '70-90', '{"Rock","Ballad"}', NULL, false, 1);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Sweet Child O’ Mine', 'Guns N’ Roses', '70-90', '{"Classic Rock"}', NULL, false, 2);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Wonderwall', 'Oasis', '70-90', '{"Sing-along","Britpop"}', 'assets/audio/demo.mp3', true, 3);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Creep', 'Radiohead (Silkadelics Version)', '70-90', '{"Alternative"}', NULL, true, 4);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Sweet Dreams', 'Marilyn Manson', '70-90', '{"Dark Pop"}', NULL, false, 5);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('What’s Up', 'People R Ugly', '70-90', '{"Anthem"}', NULL, false, 6);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Ouvi Dizer', 'Ornatos Violeta', '70-90', '{"Português"}', NULL, false, 7);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Chaga', 'Ornatos Violeta', '70-90', '{"Português"}', NULL, false, 8);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('All The Small Things', 'Blink-182', '70-90', '{"Pop Punk"}', NULL, false, 9);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Freed From Desire', 'Gala', '70-90', '{"Dance","90s"}', NULL, true, 10);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Crawling', 'Linkin Park', '2000+', '{"Rock","Nu-Metal"}', NULL, false, 11);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Numb', 'Linkin Park', '2000+', '{"Anthem","Nu-Metal"}', 'assets/audio/demo.mp3', true, 12);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('What I’ve Done', 'Linkin Park', '2000+', '{"Rock"}', NULL, false, 13);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Fix You', 'Coldplay', '2000+', '{"Emotional","Pop"}', NULL, true, 14);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Yellow', 'Coldplay', '2000+', '{"Acoustic","Classic"}', NULL, true, 15);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('In The Shadows', 'The Rasmus', '2000+', '{"Rock"}', NULL, false, 16);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Holiday', 'Green Day', '2000+', '{"Punk Rock"}', NULL, true, 17);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Boulevard Of Broken Dreams', 'Green Day', '2000+', '{"Rock"}', NULL, true, 18);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Kryptonite', '3 Doors Down', '2000+', '{"Alternative"}', NULL, false, 19);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Plug In Baby', 'Muse', '2000+', '{"Rock","Modern"}', NULL, false, 20);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Hysteria', 'Muse', '2000+', '{"Rock"}', NULL, false, 21);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Time Is Running Out', 'Muse', '2000+', '{"Rock"}', NULL, false, 22);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Lonely Day', 'System Of A Down', '2000+', '{"Rock"}', NULL, false, 23);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Aerials', 'System Of A Down', '2000+', '{"Rock"}', NULL, false, 24);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Killing In The Name', 'Rage Against The Machine', '2000+', '{"Heavy"}', NULL, false, 25);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Everlong', 'Foo Fighters', '2000+', '{"Rock"}', NULL, false, 26);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Use Somebody', 'Kings Of Leon', '2000+', '{"Indie Rock"}', NULL, true, 27);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Sex On Fire', 'Kings Of Leon', '2000+', '{"Anthem"}', NULL, true, 28);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('One More Time', 'Daft Punk', '2000+', '{"Dance"}', NULL, true, 29);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Naive', 'The Kooks', '2000+', '{"Indie"}', NULL, false, 30);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('R U Mine?', 'Arctic Monkeys', '2000+', '{"Rock"}', NULL, false, 31);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Ordinary Love', 'U2', '2010+', '{"Pop"}', NULL, false, 32);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Way Down We Go', 'Kaleo', '2010+', '{"Blues Rock"}', NULL, false, 33);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('No Good', 'Kaleo', '2010+', '{"Rock"}', NULL, true, 34);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Beggin', 'Måneskin', '2010+', '{"Rock","Trend"}', NULL, true, 35);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Wanna Be Your Slave', 'Måneskin', '2010+', '{"Rock"}', NULL, false, 36);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Let’s Get It Started', 'Måneskin', '2010+', '{"Party"}', NULL, false, 37);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Creep', 'Radiohead (Silkadelics Version)', '2010+', '{"Alternative"}', NULL, false, 38);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Rolling In The Deep (Linkin Park)', 'Adele', '2010+', '{"Emotional"}', NULL, false, 39);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Shut Up And Dance', 'Walk The Moon', '2010+', '{"Party","Dance"}', NULL, true, 40);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Moves Like Jagger', 'Maroon 5', '2010+', '{"Pop"}', NULL, false, 41);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Sugar', 'Maroon 5', '2010+', '{"Wedding Pop"}', NULL, false, 42);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Can’t Stop The Feeling', 'Justin Timberlake', '2010+', '{"Dance","Pop"}', NULL, false, 43);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Super Bowl Halftime Medley', 'Bruno Mars', '2010+', '{"Funk","Party"}', 'assets/audio/demo.mp3', true, 44);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('What You Know', 'Two Door Cinema Club', '2010+', '{"Indie"}', NULL, true, 45);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Riptide', 'Vance Joy', '2010+', '{"Acoustic"}', NULL, false, 46);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Snap Out Of It', 'Arctic Monkeys', '2010+', '{"Indie Rock"}', NULL, false, 47);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Mr. Brightside', 'The Killers', '2010+', '{"Anthem","Party"}', 'assets/audio/demo.mp3', true, 48);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Get Lucky', 'Daft Punk', '2010+', '{"Funk","Disco"}', NULL, true, 49);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Zombie', 'Bad Wolves', '2010+', '{"Rock"}', NULL, true, 50);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Baby One More Time', 'Tenacious D', '2010+', '{"Funny","Rock"}', NULL, true, 51);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Duia', 'The weasel (Silkadelics Version)', '2010+', '{"Português"}', NULL, false, 52);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Haja O Que Houver', 'Silkadelics Version', '2010+', '{"Português"}', NULL, false, 53);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Anda Comigo Ver os Aviões', 'Os Azeitonas', '2010+', '{"Português"}', NULL, false, 54);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Black', 'Pearl Jam', '2010+', '{"Rock"}', NULL, false, 55);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('What''s Up', 'People R Ugly', 'Pop / Indie', '{}', NULL, true, 56);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Sweet Child O'' Mine', 'Guns N'' Roses', 'Pop / Indie', '{}', NULL, true, 57);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Take Me Out', 'Franz Ferdinand', 'Pop / Indie', '{}', NULL, true, 58);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Duia', 'The Weasel (Silkadelics Version)', 'Pop / Indie', '{}', NULL, true, 59);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Can''t Stop The Feeling', 'Justin Timberlake', 'Pop / Indie', '{}', NULL, true, 60);
INSERT INTO repertoire (title, artist, category, tags, audio_url, is_recommended, display_order) VALUES ('Let''s Get It Started', 'Måneskin', 'Pop / Indie', '{}', NULL, true, 61);
