-- Populate Repertoire Table
INSERT INTO repertoire (title, artist, category, display_order) VALUES
('Valerie', 'Amy Winehouse', 'Soul / Funk / Blues', 1),
('Like a Stone', 'Audioslave', 'Rock / Alternative', 2),
('Yellow', 'Coldplay', 'Pop / Indie', 3),
('Don''t Panic', 'Coldplay', 'Pop / Indie', 4),
('Trouble', 'Coldplay', 'Pop / Indie', 5),
('Haja o que Houver', 'Diogo Leite', 'Portuguesa', 6),
('Enemy', 'Imagine Dragons', 'Pop / Indie', 7),
('Whatever It Takes', 'Imagine Dragons', 'Pop / Indie', 8),
('Anna Molly', 'Incubus', 'Rock / Alternative', 10),
('Sex On Fire', 'Kings of Leon', 'Rock / Alternative', 11),
('New Divide', 'Linkin Park', 'Rock / Alternative', 12),
('One More Light', 'Linkin Park', 'Rock / Alternative', 13),
('Gossip', 'Maneskin', 'Rock / Alternative', 14),
('Wanna Be Your Slave', 'Maneskin', 'Rock / Alternative', 15),
('Brother', 'Matt Corby', 'Soul / Funk / Blues', 16),
('Cold Little Heart', 'Michael Kiwanuka', 'Soul / Funk / Blues', 17),
('Time Is Running Out', 'Muse', 'Rock / Alternative', 18),
('Olá Solidão', 'Os Quatro e Meia', 'Portuguesa', 19),
('Somebody Told Me', 'The Killers', 'Rock / Alternative', 20),
('Naive', 'The Kooks', 'Pop / Indie', 21),
('Sweather Weather', 'The Neighbourhood', 'Pop / Indie', 22),
('Wicked Game', 'Stone Sour', 'Rock / Alternative', 23),
('Through The Glass', 'Stone Sour', 'Rock / Alternative', 24),
('The Kill', 'Thirty Seconds To Mars', 'Rock / Alternative', 25),
('Closer To The Edge', 'Thirty Seconds To Mars', 'Rock / Alternative', 26),
('What You Know', 'Two Doors Cinema Club', 'Pop / Indie', 27),
('Riptide', 'Vance Joy', 'Pop / Indie', 28),
('Aerials', 'System of a Down', 'Rock / Alternative', 29),
('Little Black Submarines', 'The Black Keys', 'Rock / Alternative', 30),
('Crawling', 'Linkin Park', 'Rock / Alternative', 31),
('In The Shadows', 'The Rasmus', 'Rock / Alternative', 32),
('Use Somebody', 'Kings Of Leon', 'Rock / Alternative', 33),
('Ordinary Love', 'U2', 'Rock / Alternative', 34),
('Duia', 'Gonçalo Bilé', 'Portuguesa', 35),
('Wonderwall', 'Oasis', 'Pop / Indie', 36),
('Fix You', 'Coldplay', 'Pop / Indie', 37),
('Way Down We Go', 'Kaleo', 'Soul / Funk / Blues', 38),
('What''s Up', 'People R Ugly', 'Rock / Alternative', 39),
('Ouvi Dizer', 'Ornatos Violeta', 'Portuguesa', 40),
('Chaga', 'Ornatos Violeta', 'Portuguesa', 41),
('Get Lucky', 'Daft Punk', 'Soul / Funk / Blues', 42),
('Beggin', 'Maneskin', 'Rock / Alternative', 43),
('Creep', 'Radiohead', 'Rock / Alternative', 44),
('Psycho', 'Muse', 'Rock / Alternative', 45),
('Hysteria', 'Muse', 'Rock / Alternative', 46),
('Black', 'Pearl Jam', 'Rock / Alternative', 47),
('Sweet Dreams', 'Marylin Manson', 'Rock / Alternative', 48),
('Everlong', 'Foo Fighters', 'Rock / Alternative', 49),
('Lithium', 'Nirvana', 'Rock / Alternative', 50),
('Lonely Day', 'System of a Down', 'Rock / Alternative', 51),
('Bring Me To Life', 'Evanescence', 'Rock / Alternative', 52),
('Holiday', 'Green Day', 'Rock / Alternative', 53),
('Boulevard of Broken Dreams', 'Green Day', 'Rock / Alternative', 54),
('Plugin Baby', 'Muse', 'Rock / Alternative', 55),
('Sweet Child O'' Mine', 'Guns N'' Roses', 'Rock / Alternative', 56),
('Zombie', 'Bad Wolves', 'Rock / Alternative', 57),
('What I''ve Done', 'Linkin Park', 'Rock / Alternative', 58),
('Numb', 'Linkin Park', 'Rock / Alternative', 59),
('No Good', 'Kaleo', 'Rock / Alternative', 60),
('Killing In The Name', 'Rage Against The Machine', 'Rock / Alternative', 61),
('R U Mine', 'Arctic Monkeys', 'Rock / Alternative', 62),
('Kryptonite', '3 Doors Down', 'Rock / Alternative', 63),
('Snap Out Of It', 'Arctic Monkeys', 'Rock / Alternative', 64),
('Lets Get Started', 'Maneskin', 'Rock / Alternative', 65),
('Enter Sandman', 'Alessia Cara & The Warning', 'Rock / Alternative', 66),
('Take Me Out', 'Franz Ferdinand', 'Rock / Alternative', 67),
('Out Of The Black', 'Royal Blood', 'Rock / Alternative', 68),
('I Was Made For Lovin'' You', 'Yungblud', 'Pop / Indie', 69);
